head_hunter/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from head_hunter import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('head_hunters.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

head_hunters/urls.py
from django.urls import path
from . import views


app_name = 'head_hunters'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topic/<slug:topic_slug>', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),

    path('new_summary/<slug:topic_slug>/', views.new_summary,
        name='new_summary'),
    path('edit_summary/<int:summary_id>', views.edit_summary,
        name='edit_summary'),
    path('show_summary/<int:summary_id>', views.show_summary,
        name='show_summary'),
    path('delete_summary/<int:summary_id>', views.delete_summary,
        name='delete_summary'),

    path('new_vacancy/<slug:topic_slug>/', views.new_vacancy,
        name='new_vacancy'),
    path('edit_vacancy/<int:vacancy_id>', views.edit_vacancy,
        name='edit_vacancy'),
    path('show_vacancy/<int:vacancy_id>', views.show_vacancy,
        name='show_vacancy'),
    path('delete_vacancy/<int:vacancy_id>', views.delete_vacancy,
        name='delete_vacancy'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

head_hunters/models.py
from pytils.translit import slugify
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True,
        verbose_name="URL")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Topic, self).save(*args, **kwargs)


class Summary(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    photo = models.ImageField(upload_to="photos/%Y/%m/%d")
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'summaries'

    def __str__(self):
        return f"{self.text[:50]}..."


class Vacancy(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=250)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'vacancies'

    def __str__(self):
        return f"{self.text[:50]}..."

head_hunters/forms.py
from django import forms
from .models import Topic, Summary, Vacancy


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name']
        labels = {'name': ''}


class SummaryForm(forms.ModelForm):
    class Meta:
        model = Summary
        fields = ['text', 'photo']
        labels = {'text': 'Summary:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = ['text']
        labels = {'text': 'Vacancy:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

head_hunters/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Summary, Vacancy
from users.models import Profile
from .forms import TopicForm, SummaryForm, VacancyForm
from .check_of_validation import check_object_owner


def index(request):
    return render(request, 'head_hunters/index.html')


@login_required
def topics(request):
    topics = Topic.objects.order_by('date_added')

    context = {'topics': topics}
    return render(request, 'head_hunters/topics.html', context=context)


@login_required
def topic(request, topic_slug):
    topic = Topic.objects.get(slug=topic_slug)
    if request.user.profile.is_employee:
        summaries = topic.summary_set.order_by('date_added')
        vacancies = topic.vacancy_set.filter(owner=request.user)\
            .order_by('date_added')
        request_for = 'head_hunters/topic_for_employee.html'
    else:
        summaries = topic.summary_set.filter(owner=request.user)\
            .order_by('date_added')
        vacancies = topic.vacancy_set.order_by('date_added')
        request_for = 'head_hunters/topic_for_individual.html'

    context = {'topic': topic, 'summaries': summaries, 'vacancies': vacancies}
    return render(request, request_for, context=context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('head_hunters:topics')

    context = {'form': form}
    return render(request, 'head_hunters/new_topic.html', context=context)


@login_required
def new_summary(request, topic_slug):
    topic = Topic.objects.get(slug=topic_slug)
    if request.method != 'POST':
        form = SummaryForm()
    else:
        form = SummaryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_summary = form.save(commit=False)
            new_summary.topic = topic
            new_summary.owner = request.user
            new_summary.save()
            return redirect('head_hunters:topic', topic_slug=topic_slug)

    context = {'topic': topic, 'form': form}
    return render(request, 'head_hunters/new_summary.html', context=context)


@login_required
def edit_summary(request, summary_id):
    summary = Summary.objects.get(id=summary_id)
    topic = summary.topic

    check_object_owner(summary, request)

    if request.method != 'POST':
        form = SummaryForm(instance=summary)
    else:
        form = SummaryForm(instance=summary, data=request.POST,
            files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('head_hunters:topic', topic_slug=topic.slug)

    context = {'summary': summary, 'topic': topic, 'form': form}
    return render(request, 'head_hunters/edit_summary.html', context=context)


@login_required
def show_summary(request, summary_id):
    summary = Summary.objects.get(id=summary_id)
    topic = summary.topic
    phone = Profile.objects\
                .get(user_id=summary.owner.id).phone_number

    context = {'summary': summary, 'topic': topic, 'phone': phone}
    return render(request, 'head_hunters/show_summary.html', context=context)


@login_required
def delete_summary(request, summary_id):
    summary = Summary.objects.get(id=summary_id)
    topic = summary.topic
    Summary.objects.filter(id=summary_id).delete()

    context = {'topic': topic}
    return render(request, 'head_hunters/delete_summary.html', context=context)


@login_required
def new_vacancy(request, topic_slug):
    topic = Topic.objects.get(slug=topic_slug)
    if request.method != 'POST':
        form = VacancyForm()
    else:
        form = VacancyForm(data=request.POST)
        if form.is_valid():
            new_vacancy = form.save(commit=False)
            new_vacancy.topic = topic
            new_vacancy.owner = request.user
            new_vacancy.company_name = Profile.objects\
                .get(user_id=request.user.id).company_name
            new_vacancy.save()
            return redirect('head_hunters:topic', topic_slug=topic_slug)

    context = {'topic': topic, 'form': form}
    return render(request, 'head_hunters/new_vacancy.html', context=context)


@login_required
def edit_vacancy(request, vacancy_id):
    vacancy = Vacancy.objects.get(id=vacancy_id)
    topic = vacancy.topic

    check_object_owner(vacancy, request)

    if request.method != 'POST':
        form = VacancyForm(instance=vacancy)
    else:
        form = VacancyForm(instance=vacancy, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('head_hunters:topic', topic_slug=topic.slug)

    context = {'vacancy': vacancy, 'topic': topic, 'form': form}
    return render(request, 'head_hunters/edit_vacancy.html', context=context)


@login_required
def show_vacancy(request, vacancy_id):
    vacancy = Vacancy.objects.get(id=vacancy_id)
    topic = vacancy.topic
    phone = Profile.objects\
                .get(user_id=vacancy.owner.id).phone_number

    context = {'vacancy': vacancy, 'topic': topic, 'phone': phone}
    return render(request, 'head_hunters/show_vacancy.html', context=context)


@login_required
def delete_vacancy(request, vacancy_id):
    vacancy = Vacancy.objects.get(id=vacancy_id)
    topic = vacancy.topic
    Vacancy.objects.filter(id=vacancy_id).delete()

    context = {'topic': topic}
    return render(request, 'head_hunters/delete_vacancy.html', context=context)

head_hunters/templates/head_hunters/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width",
            initial-scale=1.0, 
            shrink-to-fit="no"
        >
        <title>Head Hunters</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light mb-4 border"
            style="background-color: #F7CBCB;">
            <a class="navbar-brand" href="{% url 'head_hunters:index' %}">HeadHunters</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto border border-danger rounded-sm">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'head_hunters:topics' %}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>

        </nav>
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

head_hunters/templates/head_hunters/delete_summary.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Delete summary</h2>
{% endblock page_header %}

{% block content %}

    <h3>
        <a href="{% url 'head_hunters:topic' topic.slug %}"
            class="nav-link">{{ topic }}</a>
    </h3>

<p>Summary was deleted</p>

{% endblock content %}

head_hunters/templates/head_hunters/delete_vacancy.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Delete vacancy</h2>
{% endblock page_header %}

{% block content %}

    <h3>
        <a href="{% url 'head_hunters:topic' topic.slug %}"
            class="nav-link">{{ topic }}</a>
    </h3>

<p>Vacancy was deleted</p>

{% endblock content %}

head_hunters/templates/head_hunters/edit_summary.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit summary</h2>
{% endblock page_header %}

{% block content %}

    <h3><a href="{% url 'head_hunters:topic' topic.slug %}" 
        class="nav-link">{{ topic }}</a></h3>

    <form action="{% url 'head_hunters:edit_summary' summary.id %}" class="form" method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

head_hunters/templates/head_hunters/edit_vacancy.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit vacancy</h2>
{% endblock page_header %}

{% block content %}

    <h3><a href="{% url 'head_hunters:topic' topic.slug %}" 
        class="nav-link">{{ topic }}</a></h3>

    <form action="{% url 'head_hunters:edit_vacancy' vacancy.id %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

head_hunters/templates/head_hunters/index.html
{% extends "head_hunters/base.html" %}

{% block page_header %}

    <div class='jumbotron' style="background-color: #FDE5E5;">
        <h1 class="display-3">Start looking for a new job here.</h1>

        <div class="lead">
            <p>The more difficult the job, the easier it is to get a job.</p>
            <p>This service will help you find a job or offer you suitable workers.</p>
        </div>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;
    </a>
    </div>

{% endblock page_header %}

head_hunters/templates/head_hunters/new_summary.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add new summary</h2>
{% endblock page_header %}

{% block content %}

    <h3>
        <a href="{% url 'head_hunters:topic' topic.slug %}">{{ topic }}</a>
    </h3>

    <form action="{% url 'head_hunters:new_summary' topic.slug %}" class="form" method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add summary</button>
        {% endbuttons %}
    </form>

{% endblock content %}

head_hunters/templates/head_hunters/new_topic.html
{% extends "head_hunters/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add new topic</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'head_hunters:new_topic' %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

head_hunters/templates/head_hunters/new_vacancy.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add new vacancy</h2>
{% endblock page_header %}

{% block content %}

    <h3>
        <a href="{% url 'head_hunters:topic' topic.slug %}">{{ topic }}</a>
    </h3>

    <form action="{% url 'head_hunters:new_vacancy' topic.slug %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add vacancy</button>
        {% endbuttons %}
    </form>

{% endblock content %}

head_hunters/templates/head_hunters/show_summary.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>
        <a href="{% url 'head_hunters:topic' topic.slug %}"
            class="nav-link">{{ topic }}</a>
    </h2>
{% endblock page_header %}

{% block content %}
    {% if summary.photo %}
        <p><img src="{{ summary.photo.url }}" class="img-fluid rounded float-start"
            width="200" height="200"></p>
    {% endif %}

    <h4>Сontact phone number: {{ phone }}</h4>

    <h3>Summary:</h3>
    
    <h4>{{ summary.text|linebreaks }}</h4>

{% endblock content %}

head_hunters/templates/head_hunters/show_vacancy.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>
        <a href="{% url 'head_hunters:topic' topic.slug %}"
            class="nav-link">{{ topic }}</a>
    </h2>
{% endblock page_header %}

{% block content %}
    <h2>
        Company name: {{ vacancy.company_name }}
    </h2>

    <h4>Сontact phone number: {{ phone }}</h4>

    <h3>Vacancy:</h3>

    <h4>{{ vacancy.text|linebreaks }}</h4>

{% endblock content %}

head_hunters/templates/head_hunters/topic_for_employee.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>{{ topic }}</h2>
{% endblock page_header %}

{% block content %}
    <h4><p>Summaries:</p></h4>

    {% for summary in summaries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ summary.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'head_hunters:show_summary' summary.id %}"
                    class="btn btn-lg btn-primary"
                    role="button">Show summary</a>
                </small>
            </h4>
            <div class="card-body">
                {{ summary.text|truncatewords:50|linebreaks }}
            </div>
        </div>
    {% empty %}
        <h4>There are no summaries for this topic yet.</h4>
    {% endfor %}


    <h4><p>My vacancies:</p></h4>
    <p>
        <a href="{% url 'head_hunters:new_vacancy' topic.slug %}"
            class="btn btn-lg btn-primary"
            role="button">Add new vacancy</a>
    </p>

    {% for vacancy in vacancies %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ vacancy.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'head_hunters:edit_vacancy' vacancy.id %}"
                        class="btn btn-lg btn-primary"
                        role="button">Edit vacancy</a>

                    <a href="{% url 'head_hunters:delete_vacancy' vacancy.id %}"
                        class="btn btn-lg btn-primary"
                        role="button">Delete vacancy</a>
                </small>
            </h4>
            <div class="card-body">
                {{ vacancy.text|truncatewords:50|linebreaks }}
            </div>
        </div>
    {% empty %}
        <h4>There are no vacancies for this topic yet.</h4>
    {% endfor %}

{% endblock content%}

head_hunters/templates/head_hunters/topic_for_individual.html
{% extends 'head_hunters/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>{{ topic }}</h2>
{% endblock page_header %}

{% block content %}
    <h4><p>My summaries:</p></h4>
    <p>
        <a href="{% url 'head_hunters:new_summary' topic.slug %}"
            class="btn btn-lg btn-primary"
            role="button">Add new summary</a>
    </p>

    {% for summary in summaries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ summary.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'head_hunters:edit_summary' summary.id %}"
                        class="btn btn-lg btn-primary"
                        role="button">Edit summary</a>
                    
                    <a href="{% url 'head_hunters:delete_summary' summary.id %}"
                        class="btn btn-lg btn-primary"
                        role="button">Delete summary</a>
                </small>
            </h4>
            <div class="card-body">
                {{ summary.text|truncatewords:50|linebreaks }}
            </div>
        </div>
    {% empty %}
        <h4>There are no summaries for this topic yet.</h4>
    {% endfor %}


    <h4><p>Vacancies:</p></h4>

    {% for vacancy in vacancies %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ vacancy.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'head_hunters:show_vacancy' vacancy.id %}"
                        class="btn btn-lg btn-primary"
                        role="button">Show vacancy</a>
                </small>
            </h4>
            <div class="card-body">
                {{ vacancy.text|truncatewords:50|linebreaks }}
            </div>
        </div>
    {% empty %}
        <h4>There are no vacancies for this topic yet.</h4>
    {% endfor %}

{% endblock content%}

head_hunters/templates/head_hunters/topics.html
{% extends "head_hunters/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'head_hunters:topic' topic.slug %}"
                    class="nav-link">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a class="btn btn-lg btn-primary" 
        href="{% url 'head_hunters:new_topic' %}" 
        role="button">Add new topic</a></h3>

{% endblock content %}